# Form implementation generated from reading ui file 'moc/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(345, 211)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.LIST_THEME = QtWidgets.QListWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LIST_THEME.setFont(font)
        self.LIST_THEME.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.LIST_THEME.setStyleSheet("QListWidget::item:hover {\n"
"                background-color: lightblue;\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"                background-color: green;\n"
"}\n"
"\n"
"QListWidget::item:pressed {\n"
"                background-color: lightcoral;\n"
"}")
        self.LIST_THEME.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.LIST_THEME.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.LIST_THEME.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.LIST_THEME.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.LIST_THEME.setAlternatingRowColors(True)
        self.LIST_THEME.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.LIST_THEME.setProperty("isWrapping", True)
        self.LIST_THEME.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.LIST_THEME.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.LIST_THEME.setWordWrap(True)
        self.LIST_THEME.setSelectionRectVisible(True)
        self.LIST_THEME.setObjectName("LIST_THEME")
        self.gridLayout.addWidget(self.LIST_THEME, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tech"))
